apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-content
data:
  index.html: |
    CANARY v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-canary
      track: canary
  template:
    metadata:
      labels:
        app: myapp-canary
        track: canary
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: content
          configMap:
            name: canary-content
