apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
  labels:
    demo: pending
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: "32"
          memory: "2Gi"
