apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-clusterip
  labels:
    app: web-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-clusterip
  template:
    metadata:
      labels:
        app: web-clusterip
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
