apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-content
data:
  index.html: |
    <html><body><p>BLUE ENVIRONMENT</p></body></html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      slot: blue
  template:
    metadata:
      labels:
        app: myapp
        slot: blue
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: content
          configMap:
            name: blue-content
